name: Send Daily Email via Resend

on:
  schedule:
    - cron: '0 12 * * *'          # 12:00 UTC 
  workflow_dispatch:             # Lets you test manually from Actions tab

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'   # or '3.12' — fine either way

      - name: Install dependencies
        run: pip install resend     # python-dotenv not needed here (no .env file in CI)

      - name: Send daily email
        env:
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          RECEIVER_EMAILS: ${{ secrets.RECEIVER_EMAILS }}   # ← Updated name
        run: python send_message.py